FROM openjdk:17-jdk-slim

WORKDIR /app

COPY target/ecommerce-0.0.1-SNAPSHOT.jar /app/app.jar

ENV DB_URL=jdbc:postgresql://postgres:5432/ecommerce
ENV DB_USERNAME=${DB_USERNAME}
ENV DB_PASSWORD=${DB_PASSWORD}
ENV DB_DRIVER_CLASS_NAME=${DB_DRIVER_CLASS_NAME}
ENV MINIO_URL=${MINIO_URL}
ENV MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
ENV MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
ENV MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
ENV SPRING_JPA_HIBERNATE_DDL_AUTO=${SPRING_JPA_HIBERNATE_DDL_AUTO}
ENV SPRING_JPA_SHOW_SQL=${SPRING_JPA_SHOW_SQL}
ENV SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=${SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT}
ENV SPRING_SERVLET_MULTIPART_ENABLED=${SPRING_SERVLET_MULTIPART_ENABLED}
ENV SPRING_SERVLET_MULTIPART_FILE_SIZE_THRESHOLD=${SPRING_SERVLET_MULTIPART_FILE_SIZE_THRESHOLD}
ENV SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE=${SPRING_SERVLET_MULTIPART_MAX_FILE_SIZE}
ENV SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE=${SPRING_SERVLET_MULTIPART_MAX_REQUEST_SIZE}
ENV LOGGING_LEVEL_ORG_SPRINGFRAMEWORK=${LOGGING_LEVEL_ORG_SPRINGFRAMEWORK}
ENV JWT_SECRET_KEY=${JWT_SECRET_KEY}
ENV JWT_EXPIRATION_TIME=${JWT_EXPIRATION_TIME}

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "app.jar"]
